let scholarships = [{
    desc: "COLLEGE BOARD INDIA SCHOLARS PROGRAM",
    country: "INDIA",
    category: "all",
    gender: "M",
    class: "12",
    state: "all over india",
    university: "mahipal etc.",
    visit_website: "https://www.collegeboard.org",
    information: "https://www.buddy4study.com/collegeboard",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "IET India Scholarship Award 2024",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.theietevents.com",
    information: "https://www.buddy4study.com/page/iet-india-scholarship-awards?utm_source=featuredBlocks",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",

},








{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "other",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "other",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "other",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "other",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "other",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "other",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR PREMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "UP SHOLARSHIP FOR POSTMATRIC",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in/RegistrationNew.aspx",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},









{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "M",
    class: "post graduation",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "11",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Aspire Leaders Program 2024",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://apply.aspireleaders.org/templates/64d671753b5d001c53000753/start",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "CENTRAL SECTOR SCHEME OF SCHOLARSHIPS FOR COLLEGE AND UNIVERSITY STUDENTS",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/CSSS_GUIDLINES_07022024_updated.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "general",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "M",
    class: "post Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},{
    desc: "COLLEGE BOARD INDIA SCHOLARS PROGRAM",
    country: "INDIA",
    category: "all",
    gender: "M,F",
    class: "12",
    state: "all over india",
    university: "mahipal etc.",
    visit_website: "https://www.collegeboard.org",
    information: "https://www.buddy4study.com/collegeboard",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP FOR SC STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "sc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in/",
    information: "https://scholarships.gov.in/public/schemeGuidelines/Assam_Post_Matric_guideline.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "PRE MATRIC SCHOLARSHIP TO OBC STUDENTS (CLASS 9 AND CLASS 10) -ASSAM",
    country: "INDIA",
    state: "assam",
    category: "obc",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/PRE_MATRIC_OBC_GUIDELINES.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "PRE MATRIC SCHOLARSHIP TO ST STUDENTS (CLASS IX AND X) - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "st",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/guidelines-Pre-matric-ST.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP TO OBC STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "obc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/POST_MATRIC_OBC_GUIDELINES.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP TO ST STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "st",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/Post-matric-guidelines-ST.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for OBC Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_qaqeTF.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "post graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "M",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "University of Sheffield International UG Merit Scholarship 2024",
    country: "UK",
    state: "South Yorkshire",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://www.sheffield.ac.uk/international/fees-and-funding/scholarships/undergraduate/international-undergraduate-merit-scholarship",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "British Council Scholarship for Women in STEM 2024",
    country: "UK",
    state: "brisbane",
    category: "all",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://www.britishcouncil.in/study-uk/scholarships/womeninstem-scholarships",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "post graduation",
    company: "",
    university: "BHU",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Merit-cum-Means Scholarships",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Ford Foundation Scholarships",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "M",
    class: "phost graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Prof. Ramesha Rao Scholarship and Travel Grant",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "phd",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Balak Ram Scholarship	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    information: "https://www.du.ac.in/uploads/scholarships/21082014_UG_1.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "*Shri Ram Lubhaya Book-Grant (Blind Students)	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "Graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    // pwd: "yes",
    information: "https://www.du.ac.in/uploads/scholarships/01092018_sh-ram-lubhaya.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Vijender Sharmila Chopra Book-Grant (Blind Students)	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    // pwd: "yes",
    information: "https://www.du.ac.in/uploads/scholarships/01092018_vijendra-sharmila-chopra.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Merit-cum-Means Scholarships",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "M",
    class: "graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "COLLEGE BOARD INDIA SCHOLARS PROGRAM",
    country: "INDIA",
    category: "all",
    gender: "F",
    class: "12",
    state: "all over india",
    university: "mahipal etc.",
    visit_website: "https://www.collegeboard.org",
    information: "https://www.buddy4study.com/collegeboard",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "IET India Scholarship Award 2024",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.theietevents.com",
    information: "https://www.buddy4study.com/page/iet-india-scholarship-awards?utm_source=featuredBlocks",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Aapki Beti Hamari Beti Scheme, Haryana",
    country: "INDIA",
    state: "haryana",
    category: "sc",
    gender: "F",
    class: "under 8",
    company: "",
    university: "",
    visit_website: "https://wcdhry.gov.in/schemes-for-children/abhb",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "F",
    class: "post graduation",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "11",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Aspire Leaders Program 2024",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://apply.aspireleaders.org/templates/64d671753b5d001c53000753/start",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "CENTRAL SECTOR SCHEME OF SCHOLARSHIPS FOR COLLEGE AND UNIVERSITY STUDENTS",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/CSSS_GUIDLINES_07022024_updated.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "general",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "General",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "F",
    class: "post Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},{
    desc: "COLLEGE BOARD INDIA SCHOLARS PROGRAM",
    country: "INDIA",
    category: "all",
    gender: "M,F",
    class: "12",
    state: "all over india",
    university: "mahipal etc.",
    visit_website: "https://www.collegeboard.org",
    information: "https://www.buddy4study.com/collegeboard",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP FOR SC STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "sc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in/",
    information: "https://scholarships.gov.in/public/schemeGuidelines/Assam_Post_Matric_guideline.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "obc",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "PRE MATRIC SCHOLARSHIP TO OBC STUDENTS (CLASS 9 AND CLASS 10) -ASSAM",
    country: "INDIA",
    state: "assam",
    category: "obc",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/PRE_MATRIC_OBC_GUIDELINES.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "PRE MATRIC SCHOLARSHIP TO ST STUDENTS (CLASS IX AND X) - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/guidelines-Pre-matric-ST.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for SC, ST & General Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "st",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_QgR22Z.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP TO OBC STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "obc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/POST_MATRIC_OBC_GUIDELINES.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "POST MATRIC SCHOLARSHIP TO ST STUDENTS - ASSAM",
    country: "INDIA",
    state: "assam",
    category: "st",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    information: "https://scholarships.gov.in/public/schemeGuidelines/Post-matric-guidelines-ST.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Pre Matric Scholarship for OBC Students, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "under 10",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_qaqeTF.pdf",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "post graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric Intermediate Scholarship for SC, ST & General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "12",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Post-Matric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2023-24",
    country: "INDIA",
    state: "uttar pradesh",
    category: "sc",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "University of Sheffield International UG Merit Scholarship 2024",
    country: "UK",
    state: "South Yorkshire",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://www.sheffield.ac.uk/international/fees-and-funding/scholarships/undergraduate/international-undergraduate-merit-scholarship",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "British Council Scholarship for Women in STEM 2024",
    country: "UK",
    state: "brisbane",
    category: "all",
    gender: "F",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://www.britishcouncil.in/study-uk/scholarships/womeninstem-scholarships",

    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "BHU",
    visit_website: "",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Banaras Hindu University (BHU)",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "post graduation",
    company: "",
    university: "BHU",
    visit_website: "https://scholarship.up.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Merit-cum-Means Scholarships",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Ford Foundation Scholarships",
    country: "INDIA",
    state: "uttar pradesh",
    category: "all",
    gender: "F",
    class: "phost graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Prof. Ramesha Rao Scholarship and Travel Grant",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "phd",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Balak Ram Scholarship	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "*Shri Ram Lubhaya Book-Grant (Blind Students)	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "Graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Vijender Sharmila Chopra Book-Grant (Blind Students)	",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "graduation",
    company: "",
    university: "DU",
    visit_website: "https://www.du.ac.in/index.php?page=opportunities-scholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Merit-cum-Means Scholarships",
    country: "INDIA",
    state: "delhi",
    category: "all",
    gender: "F",
    class: "graduation",
    company: "",
    university: "JNU",
    visit_website: "https://www.jnu.ac.in/content/fellowshipsscholarships",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "COLLEGE BOARD INDIA SCHOLARS PROGRAM",
    country: "INDIA",
    category: "all",
    gender: "other",
    class: "12",
    state: "all over india",
    university: "mahipal etc.",
    visit_website: "https://www.collegeboard.org",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "IET India Scholarship Award 2024",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.theietevents.com",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "other",
    class: "phd",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Aapki Beti Hamari Beti Scheme, Haryana",
    country: "INDIA",
    state: "haryana",
    category: "sc",
    gender: "other",
    class: "under 8",
    company: "",
    university: "",
    visit_website: "https://wcdhry.gov.in/schemes-for-children/abhb",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Scholarship by govt of india",
    country: "INDIA",
    state: "all over india",
    category: "all",
    gender: "other",
    class: "Graduation",
    company: "",
    university: "",
    visit_website: "https://scholarships.gov.in",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
},
{
    desc: "Gujarat Government’s Study Abroad Loan Scheme",
    country: "INDIA",
    state: "Gujarat",
    category: "all",
    gender: "other",
    class: "post graduation",
    company: "",
    university: "",
    visit_website: "https://sje.gujarat.gov.in/ddcw/schemes",
    photo: "phtos/WhatsApp Image 2024-04-17 at 14.01.04_adc626ca.jpg",
    information: "https://s3-ap-southeast-1.amazonaws.com/cdn.buddy4study.com/static/scholarship_docs/download-form_O58u5H.pdf",
}
];

function matchAndDisplay(data, country, state, gender, scholarshipClass, category) {
    let linksContainer = document.getElementById('linksContainer');
    if (!linksContainer) {
        linksContainer = document.createElement('div');
        linksContainer.id = 'linksContainer';
        document.body.appendChild(linksContainer);
    } else {
        linksContainer.innerHTML = ''; 
    }

    let matchedElements = [];

    for (let i = 0; i < data.length; i++) {
        let element = data[i];
        if (element.country === country &&
            element.state === state &&
            element.gender === gender &&
            element.class === scholarshipClass &&
            element.category === category) {
            matchedElements.push(element);
        }
    }

    if (matchedElements.length > 0) {
        for (let scholarship of matchedElements) {
            let imageContainer = document.createElement('div');
            imageContainer.classList.add('image-container');

            let image = document.createElement('img');
            image.src = scholarship.photo;
            imageContainer.appendChild(image);

            let descText = document.createElement('div');
            descText.textContent = scholarship.desc;
            descText.classList.add('description');
            imageContainer.appendChild(descText);

            let visitLink = document.createElement('a');
            visitLink.href = scholarship.visit_website;
            visitLink.textContent = "Visit Link";
            visitLink.classList.add('visit-link');
            imageContainer.appendChild(visitLink);

            let information = document.createElement('a');
            information.href = scholarship.information;
            information.textContent = "information";
            information.classList.add('information');
            imageContainer.appendChild(information);

            linksContainer.appendChild(imageContainer);
        }
    } else {
        let noResultMessage = document.createElement('p');
        noResultMessage.textContent = 'There are no scholarships available matching the entered criteria.';
        linksContainer.appendChild(noResultMessage);
    }
}

function refresh() {
    let country = document.getElementById('country').value.trim();
    let state = document.getElementById('state').value.trim();
    let gender = document.getElementById('gender').value.trim();
    let scholarshipClass = document.getElementById('present_class').value.trim();
    let category = document.getElementById('category').value.trim();

    matchAndDisplay(scholarships, country, state, gender, scholarshipClass, category); 
}